### ISSUE TITLE
Error in running flutter pub get

### ISSUE THREAD

**Issue by odejinmi** [SirusCodes/mobile_web_view#2]
Running "flutter pub get" in mobile_web_view...                 
Error on line 38, column 3 of pubspec.yaml: A package may not list itself as a dependency.
   ╷
38 │   mobile_web_view: 
   │   ^^^^^^^^^^^^^^^
   ╵
pub get failed (65;    ╵)

**Comment by SirusCodes** [comment]
Hey @odejinmi there is some issue with how you are writing the dependency.

`.yaml` files are space sensitive.

I would recommend you to check the spacing in your file or use CLI to add dependency.
`flutter pub add mobile_web_view`
Running the above command will add the package to your dependency list

**Comment by odejinmi** [comment]
when i use the command line own i'm still having another issue 

Because mobile_web_view depends on mobile_web_view, version solving failed.
pub finished with exit code 65

<img width="1440" alt="Screen Shot 2022-05-09 at 10 48 01 PM" src="https://user-images.githubusercontent.com/45696129/167504615-0f495883-7a09-447a-8413-3c966febc02f.png">
